[package]
name = "blockchain-in-rust"
version = "0.1.0"
authors = ["s"]
edition = "2021"

[lib]
name = "blockchainlibrary"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
crypto-hash = "0.3.4"